name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - eduardo
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo "upload actions 😎"

      - name: Install dependencies
        run: npm i

      - name: Run Test
        run: npm test
